name: bump2version-action
description: Increment the version in one or several files using bump2version, commit, tag, and push the change.
# version: 1.0.5
author: Fragile Tech
inputs:
  current_version:
    description: Version of the project *before* the bump.
    required: true 
  files:
    description: List of files in which to bump the version. The format is a concatenation of paths separated by a whitespace character.
    required: true
  commit_name:
    description: Name of the identity that is used in the commit's author signature.
    required: true
  commit_email:
    description: Email of the identity that is used in the commit's author signature.
    required: true
  login:
    description: GitHub user name of the identity. `bump-version` uses it together with `token` to push to the repository.
  token:
    description: GitHub personal access token of the identity. `bump-version` uses it together with `login` to push to the repository.
    required: true
  part:
    description: Part of the semantic version to bump.
    required: false
    default: patch
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set -x
      git config --global user.name "${{ inputs.commit_name }}"
      git config --global user.email "${{ inputs.commit_email }}"
      git config --global pull.rebase false
      BRANCH=${GITHUB_REF#refs/heads/}
      pip install --no-cache-dir bump2version
      git remote add ${{ inputs.login }} https://${{ inputs.login }}:${{ inputs.token }}@github.com/$GITHUB_REPOSITORY
      git pull --no-edit ${{ inputs.login }} $BRANCH
      git diff
      for file in ${{ inputs.files }}; do ~/.local/bin/bumpversion --allow-dirty --current-version ${{ inputs.current_version }} ${{ inputs.part }} $file; done
      git diff
      ~/.local/bin/bumpversion --tag --current-version ${{ inputs.current_version }} --commit --allow-dirty --commit-args="-a" ${{ inputs.part }}
      git push --tags ${{ inputs.login }} HEAD:$BRANCH
branding:
  color: purple
  icon: bar-chart-2
